-- BD Radar: configuration seed (footprint, score weights, settings, sources).

-- Footprint. Phase 1 = every state east of the Mississippi River, plus DC,
-- Louisiana, Arkansas and Texas. Minnesota straddles the river and is left
-- off; flip `enabled` in /settings to add it or any other state.
insert into bd.footprint (state, state_name, enabled, team) values
  ('AL', 'Alabama', true, 'East'),
  ('AK', 'Alaska', false, null),
  ('AZ', 'Arizona', false, null),
  ('AR', 'Arkansas', true, 'East'),
  ('CA', 'California', false, null),
  ('CO', 'Colorado', false, null),
  ('CT', 'Connecticut', true, 'East'),
  ('DE', 'Delaware', true, 'East'),
  ('DC', 'District of Columbia', true, 'East'),
  ('FL', 'Florida', true, 'East'),
  ('GA', 'Georgia', true, 'East'),
  ('HI', 'Hawaii', false, null),
  ('ID', 'Idaho', false, null),
  ('IL', 'Illinois', true, 'East'),
  ('IN', 'Indiana', true, 'East'),
  ('IA', 'Iowa', false, null),
  ('KS', 'Kansas', false, null),
  ('KY', 'Kentucky', true, 'East'),
  ('LA', 'Louisiana', true, 'East'),
  ('ME', 'Maine', true, 'East'),
  ('MD', 'Maryland', true, 'East'),
  ('MA', 'Massachusetts', true, 'East'),
  ('MI', 'Michigan', true, 'East'),
  ('MN', 'Minnesota', false, null),
  ('MS', 'Mississippi', true, 'East'),
  ('MO', 'Missouri', false, null),
  ('MT', 'Montana', false, null),
  ('NE', 'Nebraska', false, null),
  ('NV', 'Nevada', false, null),
  ('NH', 'New Hampshire', true, 'East'),
  ('NJ', 'New Jersey', true, 'East'),
  ('NM', 'New Mexico', false, null),
  ('NY', 'New York', true, 'East'),
  ('NC', 'North Carolina', true, 'East'),
  ('ND', 'North Dakota', false, null),
  ('OH', 'Ohio', true, 'East'),
  ('OK', 'Oklahoma', false, null),
  ('OR', 'Oregon', false, null),
  ('PA', 'Pennsylvania', true, 'East'),
  ('RI', 'Rhode Island', true, 'East'),
  ('SC', 'South Carolina', true, 'East'),
  ('SD', 'South Dakota', false, null),
  ('TN', 'Tennessee', true, 'East'),
  ('TX', 'Texas', true, 'East'),
  ('UT', 'Utah', false, null),
  ('VT', 'Vermont', true, 'East'),
  ('VA', 'Virginia', true, 'East'),
  ('WA', 'Washington', false, null),
  ('WV', 'West Virginia', true, 'East'),
  ('WI', 'Wisconsin', true, 'East'),
  ('WY', 'Wyoming', false, null);

-- Score weights. Rows marked "(assumption)" fill gaps in the agreed rubric;
-- change them in /settings.
insert into bd.score_weights (key, factor, points, description, sort_order) values
  ('fit_technology',       'fit',    10, 'Technology in scope (solar, wind, BESS, data center)', 10),
  ('fit_footprint',        'fit',     5, 'State is in the active footprint', 11),
  ('fit_size',             'fit',     5, 'At or above the MW floor (data centers always qualify)', 12),

  ('stage_queue_recent',   'stage',  15, 'Queue entry within 12 months', 20),
  ('stage_queue_old',      'stage',   5, 'Queue entry older than 12 months (assumption)', 21),
  ('stage_state_prefiling','stage',  20, 'State pre-filing', 22),
  ('stage_local_preapp',   'stage',  20, 'Local pre-application', 23),
  ('stage_filed',          'stage',  15, 'Filed, no hearing yet', 24),
  ('stage_hearing',        'stage',  15, 'Hearing scheduled (assumption: same as filed)', 25),
  ('stage_contested',      'stage',  20, 'Contested', 26),
  ('stage_denied_recent',  'stage',  18, 'Denied or tabled within 12 months', 27),
  ('stage_denied_old',     'stage',   0, 'Denied or tabled more than 12 months ago (assumption)', 28),
  ('stage_moratorium',     'stage',  18, 'Blocked by a moratorium (assumption: same as denied)', 29),
  ('stage_approved',       'stage',   5, 'Approved (Watch bucket)', 30),
  ('stage_withdrawn',      'stage',   0, 'Withdrawn', 31),

  ('pain_restriction',     'pain',   10, 'County has a Sabin restriction', 40),
  ('pain_moratorium',      'pain',   15, 'Active moratorium in the county', 41),
  ('pain_opposition',      'pain',   15, 'Opposition group or petition found', 42),
  ('pain_prior_denial',    'pain',    5, 'Prior denial in this county for the same technology', 43),
  ('pain_cap',             'pain',   25, 'Cap on total pain points', 49),

  ('access_strength_3',    'access', 25, 'Known person at developer, relationship strength 3', 50),
  ('access_strength_2',    'access', 15, 'Known person at developer, relationship strength 2', 51),
  ('access_strength_1',    'access',  8, 'Known person at developer, relationship strength 1', 52),
  ('access_known_dev',     'access', 10, 'Developer is a past client or known to RenUSA', 53),
  ('access_people_event',  'access', 10, 'Known person linked to this developer in the last 90 days', 54),
  ('access_cap',           'access', 25, 'Cap on total access points', 59),

  ('competition_penalty',  'competition', 10, 'Another engagement or digital firm is already on it (subtracted)', 60);

insert into bd.settings (key, value, description) values
  ('mw_floor',            '50',   'Minimum MW for solar, wind and BESS. Data centers have no floor.'),
  ('qualify_threshold',   '70',   'Score at which a lead alerts and auto-moves from Signal to Qualified.'),
  ('signal_threshold',    '50',   'Leads below this score are hidden by default.'),
  ('owners',              '["Dave", "Kate", "Ben"]', 'People who can own a lead.'),
  ('alert_recipients',    '["dave@renusa.org"]', 'Email addresses for the daily and Friday alerts. The ALERT_RECIPIENTS env var overrides this.');

insert into bd.sources (key, label, cadence, engine, enabled, footprint, notes) values
  ('pjm_queue',         'PJM interconnection queue',            'weekly',  'cron',   true,  '{all}', 'services.pjm.com queue export (the file behind the PJM New Services Queue page).'),
  ('sabin',             'Sabin Center Opposition Report',       'monthly', 'cron',   true,  '{all}', 'Restriction and Contested Project files from oppositionreport.org.'),
  ('greenlight',        'Greenlight Weekly (Clean Up Marketing)','weekly', 'claude', true,  '{all}', 'Claude task reads the Wednesday newsletter from Gmail.'),
  ('miso_queue',        'MISO interconnection queue',           'weekly',  'cron',   false, '{all}', 'Not built yet.'),
  ('nyiso_queue',       'NYISO interconnection queue',          'weekly',  'cron',   false, '{all}', 'Not built yet.'),
  ('isone_queue',       'ISO-NE interconnection queue',         'weekly',  'cron',   false, '{all}', 'Not built yet.'),
  ('ercot_gis',         'ERCOT GIS report',                     'weekly',  'cron',   false, '{all}', 'Not built yet.'),
  ('ercot_large_load',  'ERCOT large-load list',                'monthly', 'cron',   false, '{all}', 'Not built yet.'),
  ('spp_queue',         'SPP interconnection queue',            'weekly',  'cron',   false, '{all}', 'Not built yet.'),
  ('southeast_utilities','Duke, Dominion, Southern, TVA queues','weekly',  'cron',   false, '{all}', 'Not built yet. Log public vs gap per utility.'),
  ('opposition_sweep',  'Opposition sweep (web search)',        'weekly',  'claude', false, '{all}', 'Claude task. Not set up yet.'),
  ('people_watch',      'People and hiring watch',              'weekly',  'claude', false, '{all}', 'Needs the RenUSA contact CSV and target-developer list.'),
  ('eia860m',           'EIA-860M planned additions',           'monthly', 'cron',   false, '{all}', 'Not built yet.'),
  ('scoring',           'Nightly rescore',                      'daily',   'cron',   true,  '{all}', 'Runs bd.run_scoring().'),
  ('daily_alert',       'Daily 70+ alert email',                'daily',   'cron',   true,  '{all}', 'Resend email to alert recipients. Skips when nothing crossed 70.');
